package aplikasi.kalkulator;
public class AplikasiKalkulator extends javax.swing.JFrame {
    public AplikasiKalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        data = new javax.swing.JTextField();
        eightBT = new javax.swing.JButton();
        sevenBT = new javax.swing.JButton();
        nineBT = new javax.swing.JButton();
        fourBT = new javax.swing.JButton();
        oneBT = new javax.swing.JButton();
        pointBT = new javax.swing.JButton();
        fiveBT = new javax.swing.JButton();
        sixBT = new javax.swing.JButton();
        twoBT = new javax.swing.JButton();
        threeBT = new javax.swing.JButton();
        zeroBT = new javax.swing.JButton();
        resetBT = new javax.swing.JButton();
        plusBT = new javax.swing.JButton();
        multiplyBT = new javax.swing.JButton();
        equalsBT = new javax.swing.JButton();
        backspaceBT = new javax.swing.JButton();
        minusBT = new javax.swing.JButton();
        shareBT = new javax.swing.JButton();
        percentageBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        eightBT.setText("8");
        eightBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBTActionPerformed(evt);
            }
        });

        sevenBT.setText("7");
        sevenBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBTActionPerformed(evt);
            }
        });

        nineBT.setText("9");
        nineBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBTActionPerformed(evt);
            }
        });

        fourBT.setText("4");
        fourBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBTActionPerformed(evt);
            }
        });

        oneBT.setText("1");
        oneBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBTActionPerformed(evt);
            }
        });

        pointBT.setText(".");
        pointBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointBTActionPerformed(evt);
            }
        });

        fiveBT.setText("5");
        fiveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBTActionPerformed(evt);
            }
        });

        sixBT.setText("6");
        sixBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBTActionPerformed(evt);
            }
        });

        twoBT.setText("2");
        twoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBTActionPerformed(evt);
            }
        });

        threeBT.setText("3");
        threeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBTActionPerformed(evt);
            }
        });

        zeroBT.setText("0");
        zeroBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBTActionPerformed(evt);
            }
        });

        resetBT.setText("C");
        resetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTActionPerformed(evt);
            }
        });

        plusBT.setText("+");
        plusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBTActionPerformed(evt);
            }
        });

        multiplyBT.setText("*");
        multiplyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBTActionPerformed(evt);
            }
        });

        equalsBT.setText("=");
        equalsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsBTActionPerformed(evt);
            }
        });

        backspaceBT.setText("B");
        backspaceBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceBTActionPerformed(evt);
            }
        });

        minusBT.setText("-");
        minusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBTActionPerformed(evt);
            }
        });

        shareBT.setText("/");
        shareBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareBTActionPerformed(evt);
            }
        });

        percentageBT.setText("%");
        percentageBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageBTActionPerformed(evt);
            }
        });

        exitBT.setText("E");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sevenBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eightBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nineBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fourBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fiveBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sixBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(twoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(threeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pointBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zeroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equalsBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiplyBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backspaceBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentageBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shareBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(plusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(multiplyBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(equalsBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(backspaceBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(minusBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(shareBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(percentageBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(exitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eightBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sevenBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nineBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pointBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eightBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBTActionPerformed
        data.setText(data.getText() + "8");
    }//GEN-LAST:event_eightBTActionPerformed

    private void sevenBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBTActionPerformed
        data.setText(data.getText() + "7");
    }//GEN-LAST:event_sevenBTActionPerformed

    private void nineBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBTActionPerformed
        data.setText(data.getText() + "9");
    }//GEN-LAST:event_nineBTActionPerformed

    private void fourBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBTActionPerformed
        data.setText(data.getText() + "4");
    }//GEN-LAST:event_fourBTActionPerformed

    private void oneBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBTActionPerformed
        data.setText(data.getText() + "1");
    }//GEN-LAST:event_oneBTActionPerformed

    private void pointBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointBTActionPerformed
        data.setText(data.getText() + ".");        
    }//GEN-LAST:event_pointBTActionPerformed

    private void fiveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBTActionPerformed
        data.setText(data.getText() + "5");
    }//GEN-LAST:event_fiveBTActionPerformed

    private void sixBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBTActionPerformed
        data.setText(data.getText() + "6");
    }//GEN-LAST:event_sixBTActionPerformed

    private void twoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBTActionPerformed
        data.setText(data.getText() + "2");
    }//GEN-LAST:event_twoBTActionPerformed

    private void threeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBTActionPerformed
        data.setText(data.getText() + "3");
    }//GEN-LAST:event_threeBTActionPerformed

    private void zeroBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBTActionPerformed
        data.setText(data.getText() + "0");
    }//GEN-LAST:event_zeroBTActionPerformed

    private void resetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTActionPerformed
        data.setText("");
    }//GEN-LAST:event_resetBTActionPerformed

    private void plusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBTActionPerformed
        number1 = Double.parseDouble(data.getText());
        data.setText("");
        kalkulator = 1;
    }//GEN-LAST:event_plusBTActionPerformed

    private void multiplyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBTActionPerformed
        number1 = Double.parseDouble(data.getText());
        data.setText("");
        kalkulator = 3;
    }//GEN-LAST:event_multiplyBTActionPerformed

    private void equalsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsBTActionPerformed
        tampilkanHasil();
    }//GEN-LAST:event_equalsBTActionPerformed

    private void backspaceBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceBTActionPerformed
        int length = data.getText().length();
        int number = data.getText().length();
        String save;
        if (length > 0) {
            StringBuilder back = new StringBuilder(data.getText());
            back.deleteCharAt(number);
            save = back.toString();
            data.setText(save);
        }
    }//GEN-LAST:event_backspaceBTActionPerformed

    private void minusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusBTActionPerformed
        number1 = Double.parseDouble(data.getText());
        data.setText("");
        kalkulator = 2;
    }//GEN-LAST:event_minusBTActionPerformed

    private void shareBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareBTActionPerformed
        number1 = Double.parseDouble(data.getText());
        data.setText("");
        kalkulator = 4;
    }//GEN-LAST:event_shareBTActionPerformed

    private void percentageBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageBTActionPerformed
        number1 = Double.parseDouble(data.getText());
        data.setText("");
        kalkulator = 5;
    }//GEN-LAST:event_percentageBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKalkulator().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspaceBT;
    private javax.swing.JTextField data;
    private javax.swing.JButton eightBT;
    private javax.swing.JButton equalsBT;
    private javax.swing.JButton exitBT;
    private javax.swing.JButton fiveBT;
    private javax.swing.JButton fourBT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minusBT;
    private javax.swing.JButton multiplyBT;
    private javax.swing.JButton nineBT;
    private javax.swing.JButton oneBT;
    private javax.swing.JButton percentageBT;
    private javax.swing.JButton plusBT;
    private javax.swing.JButton pointBT;
    private javax.swing.JButton resetBT;
    private javax.swing.JButton sevenBT;
    private javax.swing.JButton shareBT;
    private javax.swing.JButton sixBT;
    private javax.swing.JButton threeBT;
    private javax.swing.JButton twoBT;
    private javax.swing.JButton zeroBT;
    // End of variables declaration//GEN-END:variables

    double number1;
    int kalkulator;

    private void tampilkanHasil(){
        double number2 = Double.parseDouble(data.getText());
        double hasil = 0;

        switch(kalkulator) {
            case 1:
                hasil = number1 + number2;
                break;
            case 2:
                hasil = number1 - number2;
                break; 
            case 3:
                hasil = number1 * number2;
                break;
            case 4:
                if(number2 != 0) {
                    hasil = number1 / number2;
                } else {
                    data.setText("Tidak bisa di bagi 0");
                }
                break;
            case 5:
                hasil = (number1 * number2) / 100;
                break;
        }
        data.setText(Double.toString(hasil));
    }
}


